contact_links:
  - name: ðŸ“š Documentation
    about: Check documentation for usage
    url: https://nuxt-apollo.nirvati.eu

  - name: ðŸ’¬ Discussions
    url: https://github.com/nirvati/nuxt-apollo/discussions
    about: Use discussions if you have an idea for improvement and asking questions
